version: 2
updates:
- package-ecosystem: "pip"
  directory: "/"
  schedule:
    interval: weekly
    timezone: Europe/Amsterdam
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 2
  versioning-strategy: lockfile-only