# Generated by Django 4.1.7 on 2023-03-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="name")),
                (
                    "date_added",
                    models.DateTimeField(auto_now_add=True, verbose_name="date added"),
                ),
                (
                    "date_completed",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="date completed",
                    ),
                ),
            ],
        ),
    ]
