name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    working-directory: ./src

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v5
      with:
        python-version: 3.12
    
    - name: Install hatch
      run: pip install hatch

    - name: Run linting
      run: hatch fmt --check

  testing:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: true
      matrix:
        python: ["3.9", "3.10", "3.11", "3.12"]
        experimental: [false]
        toxenv: ["py"]
        include:
          # Test against future django-crispy-forms. Allowed to fail.
          - python: "3.12"
            toxenv: crispymain
            experimental: true
          # Test against future django-tables2. Allowed to fail.
          - python: "3.12"
            toxenv: tables2main
            experimental: true
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
           python-version: '${{ matrix.python }}'

      - name: Install dependencies
        run: |
          python -m pip install tox coverage

      - name: Run tox targets for Python ${{ matrix.python }}
        run: |
          # Run only the tox environments that match the Python version
          tox run -f py$(echo ${{ matrix.python }} | tr -d .)
          coverage combine
          coverage report
          # Codecov does not support the .coverage file generated by coverage, so we convert it to xml
          coverage xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
